#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 test-all-distros path/to/deb"
    exit 1
fi

deb=$1

distributions=(
	"ubuntu:24.04"
	"debian:sid"
)

for distro in "${distributions[@]}"; do
	./build "$distro"
	./run $deb ${distro}-millisecond
done
