name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install dh-python
        sudo apt install python3-all
        sudo apt install meson 
        sudo apt install ninja-build
        sudo apt install libgtk-4-dev
        sudo apt install libadwaita-1-dev
        sudo apt install python3-gi
        sudo apt install gir1.2-gtk-4.0 
        sudo apt install gir1.2-adw-1
        sudo apt install adwaita-icon-theme
        sudo apt install meson ninja-build
        sudo apt install build-essential
        sudo apt install flatpak flatpak-builder
        sudo apt install devscripts debhelper

    - name: Configure project with Meson
      run: meson setup build

    - name: Install Flatpak dependencies
      run: |
        flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        flatpak install --user org.gnome.Sdk/x86_64/48

    - name: Build the project
      run: meson compile -C build

    - name: Build .deb package
      run: make rebuild-deb

    - name: Build Flatpak package
      run: make flatpak

    - name: Archive build artifacts
      run: |
        mkdir artifacts
        cp build-aux/deb/*/*.deb artifacts/millisecond.deb
        cp build-aux/flatpak/release/*/Millisecond.flatpak artifacts/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload .deb to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/millisecond.deb
        asset_name: millisecond_${{ github.ref_name }}.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload Flatpak to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/Millisecond.flatpak
        asset_name: Millisecond_${{ github.ref_name }}.flatpak
        asset_content_type: application/octet-stream

